version: "3.9"

name: Socialapi

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    env_file:
      - .env 
    networks:
      - my-api-net

  postgres_db:
    image: postgres:latest
    restart: always
    container_name: PostgresCont
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - my-api-net

volumes:
  postgres_db:
    driver: local

networks:
  my-api-net:
